#.travis.yml
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8.9.1"

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng e2e
  - ng build --prod --aot

notifications:
  email:
    on_failure: change
    on_success: change